m_mTCP_base:
    path: /mobbern-tcp
    defaults: { _controller: design.designTCP.controller:base }

m_mTCP_settings:
    pattern: /mobbern-tcp/settings
    defaults: { _controller: design.designTCP.controller.settings:manage }

m_Mobbern_home:
  pattern: ../
