services:
    captcha.factory:
        class: src\captcha\factory
        arguments:
            - @service_container
            - @captcha.plugins.service_collection

# ----- Captcha plugins -----
# Scope MUST be prototype for all the plugins to work.
    captcha.plugins.service_collection:
        class: src\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: captcha.plugins }

    core.captcha.plugins.gd:
        class: src\captcha\plugins\gd
        scope: prototype
        calls:
            - [set_name, [core.captcha.plugins.gd]]
        tags:
            - { name: captcha.plugins }

    core.captcha.plugins.gd_wave:
        class: src\captcha\plugins\gd_wave
        scope: prototype
        calls:
            - [set_name, [core.captcha.plugins.gd_wave]]
        tags:
            - { name: captcha.plugins }

    core.captcha.plugins.nogd:
        class: src\captcha\plugins\nogd
        scope: prototype
        calls:
            - [set_name, [core.captcha.plugins.nogd]]
        tags:
            - { name: captcha.plugins }

    core.captcha.plugins.qa:
        class: src\captcha\plugins\qa
        scope: prototype
        arguments:
            - %tables.captcha_qa_questions%
            - %tables.captcha_qa_answers%
            - %tables.captcha_qa_confirm%
        calls:
            - [set_name, [core.captcha.plugins.qa]]
        tags:
            - { name: captcha.plugins }

    core.captcha.plugins.recaptcha:
        class: src\captcha\plugins\recaptcha
        scope: prototype
        calls:
            - [set_name, [core.captcha.plugins.recaptcha]]
        tags:
            - { name: captcha.plugins }
