services:
    mimetype.guesser_collection:
        class: src\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: mimetype.guessers }

    mimetype.fileinfo_mimetype_guesser:
        class: Symfony\Component\HttpFoundation\File\MimeType\FileinfoMimeTypeGuesser
        tags:
            - { name: mimetype.guessers }

    mimetype.filebinary_mimetype_guesser:
        class: Symfony\Component\HttpFoundation\File\MimeType\FileBinaryMimeTypeGuesser
        tags:
            - { name: mimetype.guessers }

    mimetype.content_guesser:
        class: src\mimetype\content_guesser
        calls:
            - [set_priority, [%mimetype.guesser.priority.low%]]
        tags:
            - { name: mimetype.guessers }

    mimetype.extension_guesser:
        class: src\mimetype\extension_guesser
        calls:
            - [set_priority, [%mimetype.guesser.priority.lowest%]]
        tags:
            - { name: mimetype.guessers }

    mimetype.guesser:
        class: src\mimetype\guesser
        arguments:
            - @mimetype.guesser_collection
